
export const Upsells = [
  {
    id: "1",
    title: "Premium Insurance Coverage",
    description: "Drive with peace of mind. Full coverage including theft, damage, and roadside assistance.",
    price: 12.99,
    currency: "$",
    icon: "🛡️",
  },
  {
    id: "2",
    title: "GPS Navigation System",
    description: "Never get lost. Premium GPS with real-time traffic updates and points of interest.",
    price: 8.99,
    currency: "$",
    icon: "🗺️",
  },
  {
    id: "3",
    title: "Additional Driver",
    description: "Share the driving. Add an additional driver to your rental agreement.",
    price: 15.00,
    currency: "$",
    icon: "👥",
  },
  {
    id: "4",
    title: "Loss Damage Waiver (LDW)",
    description: "For collision damages, scratches, bumps and theft. Enjoy the peace of mind of knowing you're protected from high costs in case your vehicle is stolen or damaged.",
    price: 19.99,
    currency: "$",
    icon: "🛡️",
  },
  {
    id: "5",
    title: "Supplemental Liability Insurance",
    description: "You are protected against claims from third parties up to a limit of USD 300,000 per accident.",
    price: 14.99,
    currency: "$",
    icon: "⚖️",
  },
  {
    id: "6",
    title: "Extended Roadside Protection",
    description: "In the case of self-caused errors that prevent further travel, SIXT will assist you getting on the road again (flat tire, empty tank or battery, lost or locked-in key).",
    price: 7.17,
    currency: "$",
    icon: "🚗",
  },
  {
    id: "7",
    title: "Personal Accident Coverage",
    description: "Both the driver and passengers of the rental vehicle are entitled to financial compensation for accident-related medical costs.",
    price: 8.00,
    currency: "$",
    icon: "🏥",
  },
  {
    id: "8",
    title: "Personal Property Coverage",
    description: "Safeguard your personal items and those of your accompanying family members from damage or loss.",
    price: 4.30,
    currency: "$",
    icon: "🎒",
  },
  
  // Convenience & Navigation
  {
    id: "9",
    title: "Toll Pass/Express Lane",
    description: "Allows unlimited use of toll roads and expressways in the US and Canada via an electronic pass.",
    price: 9.03,
    currency: "$",
    icon: "🛣️",
  },
  {
    id: "10",
    title: "GPS Navigation System",
    description: "Built-in navigation system to ensure reliable, on-time arrival.",
    price: 7.21,
    currency: "$",
    icon: "🗺️",
  },
  {
    id: "11",
    title: "Additional Driver",
    description: "Allows a second person to drive the vehicle (must show valid license).",
    price: 9.31,
    currency: "$",
    icon: "👥",
  },
  
  // Child Safety Seats
  {
    id: "12",
    title: "Infant Seat",
    description: "Rear-facing seat for babies up to 15 months old (height up to 32 inches/81 cm).",
    price: 3.41,
    currency: "$",
    icon: "👶",
  },
  {
    id: "13",
    title: "Toddler Seat",
    description: "For children aged 6 months to 4 years (height up to 49 inches/124 cm).",
    price: 3.41,
    currency: "$",
    icon: "🧒",
  },
  {
    id: "14",
    title: "Booster Seat",
    description: "For children aged 4 to 12 years (height 43–57 inches/110–145 cm).",
    price: 3.41,
    currency: "$",
    icon: "🚸",
  },
  {
    id: "15",
    title: "Pre-paid Fuel",
    description: "Skip the gas station! Return your vehicle with any fuel level. We'll refill it for you at competitive rates.",
    price: 45.00,
    currency: "$",
    icon: "⛽",
  },
  {
    id: "16",
    title: "Wi-Fi Hotspot",
    description: "Stay connected on the go. Mobile Wi-Fi device with unlimited data for up to 5 devices.",
    price: 8.95,
    currency: "$",
    icon: "📶",
  },
  {
    id: "17",
    title: "Express Return",
    description: "Skip the return counter. Drop off your keys and go - we'll handle the rest with our mobile check-out service.",
    price: 12.50,
    currency: "$",
    icon: "🚀",
  },
];