import { GoogleGenAI } from "@google/genai";
import express from "express";
import cors from "cors";
import dotenv from "dotenv";

dotenv.config(); // Load .env variables

const app = express();
const port = 3000;

// Allow your Vite app (usually localhost:5173) to talk to this server
app.use(cors());
app.use(express.json());

const ai = new GoogleGenAI({ apiKey: process.env.VITE_GOOGLE_API_KEY });

app.post("/api/generate-background", async (req, res) => {
  try {
    const { imageUrl, userInfo } = req.body;
    console.log(`Processing image for: ${userInfo.role} at ${userInfo.location}`);

    // 1. Fetch the image data (Server-side fetch bypasses CORS)
    const imageResp = await fetch(imageUrl);
    if (!imageResp.ok) throw new Error("Failed to fetch source image");
    const arrayBuffer = await imageResp.arrayBuffer();
    
    // Convert to Base64 for Gemini
    const base64Image = Buffer.from(arrayBuffer).toString("base64");

    // 2. Construct the Prompt
    const promptText = `Create a Backgound for the attached image. 
  Context: The vehicle is located in ${userInfo.location} at ${userInfo.time}.The enviroment should be ${userInfo.enviroment}.
  Style: Realistic, Cinematic Lighting, No Black Bars.
  Do not change the vehicle itself. Focus on enhancing the background only.`;

    // 3. Call Gemini
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-image",
      contents: [
        { text: promptText },
        {
          inlineData: {
            mimeType: "image/png",
            data: base64Image,
          },
        },
      ],
    });

    // 4. Send result back to Frontend
    const part = response.candidates?.[0]?.content?.parts?.find((p) => p.inlineData);
    
    if (part && part.inlineData) {
      res.json({ success: true, image: part.inlineData.data });
    } else {
      throw new Error("No image generated by AI");
    }

  } catch (error) {
    console.error("Server Error:", error);
    res.status(500).json({ success: false, error: error.message });
  }
});

app.listen(port, () => {
  console.log(`Proxy Server running at http://localhost:${port}`);
});